language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t amellal/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true amellal/docker-react npm run test